# Generated by Django 3.0.5 on 2020-07-26 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_addressdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.AddressDetails'),
        ),
    ]
